### ISSUE TITLE
Recording little blurry

### ISSUE THREAD

**Issue by roland-rollo** [russelltg/wl-screenrec#3]
I noticed that recordings are not as sharp as original source and colors are little faded. I checked and `wf-recorder` do the same. Is it a matter of using some flag or configuring something?

This is screenshot from workspace:
![ps_20230116011629](https://user-images.githubusercontent.com/44477799/215240396-212e6428-2dc3-4cd1-93c9-76760fe3c5da.png)

**Comment by roland-rollo** [comment]
And this is screen from recording
![ps_20230116011631](https://user-images.githubusercontent.com/44477799/215240442-5f639f6a-2ccd-4906-abee-1b23d39d2108.png)

**Comment by russelltg** [comment]
That's interesting, I dug a little deeper and there may be something I can improve on--see this screenshot of various encoding methods of your screenshot you sent:

Left is original, top right is your output from wl-screenrec, middle is output from encoding with vaapi with ffmpeg, bottom right is encoding with x264. The wl-screenrec one does seem to be a bit undersaturated I think. I'm not entirely sure why.

I will note that some amount of blurring is always going to happen, because there is pixelformat compression being applied here (RGB (24 bits per pixel) -> NV12 (12 bits per pixel) as well as normal video compression. 

Probably one of the most reasonable things I could do to get higher quality outputs is to encode with HEVC (or AV1, my hardware does not support it though). Although I personally prefer to stay in h.264 land which is compatible with just about everything at this point--don't have to worry about messaging apps supporting it, etc. 

![image](https://user-images.githubusercontent.com/7105082/216799975-d2ce2d2f-4be0-4478-a86e-19b6426d414f.png)

**Comment by roland-rollo** [comment]
Thanks for explanation. That's all OK for me. I was more worried, that I do something wrong.

**Comment by russelltg** [comment]
If your machine supports it, I just added support for alternate pixel formats in https://github.com/russelltg/wl-screenrec/commit/7079f494683c13a6ca6147967b6c4c85376dc594 which means the color planes are the same resolution as the luma planes (instead of half resolution).
